Backport libarchive#2101
conda-forge/libarchive-feedstock pull request #85
Opened 2024-03-31 09:56 UTC by jjerphan

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

2024-03-31 09:56 UTC, jjerphan commented
@conda-forge-admin, please rerender

2024-03-31 11:30 UTC, beckermr requested changes
Let's wait for upstream guidance.

2024-04-02 15:49 UTC, jjerphan commented
FYI, several distributions have back ported this change or revert the original PR, including:
 - [Gentoo](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=43c399629fb022b7519d70194cb6c0364809764d)
 - [MacPorts](https://github.com/macports/macports-ports/pull/23299)
 - [homebrew-core](https://github.com/Homebrew/homebrew-core/pull/167666)
 - [archlinux](https://gitlab.archlinux.org/archlinux/packaging/packages/libarchive/-/commit/cadc187f686c010f511684819397d4ff3305f3e2)

2024-04-02 22:35 UTC, beckermr commented
It appears all commits were re-reviewed and only the patch above has been applied?

https://github.com/libarchive/libarchive/issues/2103

2024-04-02 22:38 UTC, beckermr commented
There was an associated bugfix in the same code areas but not specifically touched: https://github.com/libarchive/libarchive/pull/2104/files

2024-04-02 22:41 UTC, beckermr commented
What do you think @conda-forge/core? Should we wait for the next release or go ahead with this patch and the one from https://github.com/libarchive/libarchive/pull/2104?

Maybe if the libarchive maintainers thought there was something to patch, they would have pushed a bugfix release?

2024-04-02 22:46 UTC, isuruf commented
Please keep the discussion in #84.

2024-05-17 08:28 UTC, closed without merging